name: .NET

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -r linux-x64
    - name: Build
      run: | 
        dotnet publish -r linux-x64 -p:PublishSingleFile=true -p:Configuration=Release --no-self-contained
        cd ..
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: bin/Release/net6.0/linux-x64/publish/

  release:
    needs: [build]
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          path: ./artifacts

      - name: Zip
        run: |
            chmod +x ./artifacts/linux/ModLinksShaVerifier
            zip -jr linux.zip ./artifacts/linux/*

      - name: Create release if a new tag is pushed
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./linux.zip
